version: "3.3"

services:
  nginx-proxy:  
    image: jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - core_net
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    environment:
      - "DEFAULT_EMAIL=default@mail.com"
      - "NGINX_PROXY_CONTAINER=nginx_proxy"
    networks:
      - core_net

networks:
  core_net:
    external: true

volumes:
  nginx-certs: {}
  nginx-vhost: {}
  nginx-html: {}
