version: "3"
services:
  web:
    build: web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - webnet
      - redisnet
  redis:
    image: "redis:alpine"
    networks:
      - redisnet
networks:
  webnet:
  redisnet:
