version: "3.7"

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    build: .
    image: blog:1.0
    volumes:
      - type: bind
        source: ./source
        target: /var/www/localhost/htdocs
    ports:
      - "80:80"
      - "443:443"
    restart: always
    env_file:
      - wordpress.env

  mysql:
    image: mysql:5.7
    #image: mysql:8.0.15
    #command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - mysql.env
volumes:
  db_data: {}
