version: "3.7"

services:
  wordpress:
    container_name: wp
    depends_on:
      - mysql
    build: .
    image: core:1.0
    #volumes:
    #  - type: bind
    #    source: ./WordPress
    #    target: /var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    env_file:
      - wordpress.env
    logging:
      driver: gelf
      options:
        gelf-address: udp://0.0.0.0:12201

  mysql:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - mysql.env
    logging:
      driver: gelf
      options:
        gelf-address: udp://0.0.0.0:12201

volumes:
  db_data: {}