version: '3'
services:
  jenkins:
    container_name: jenkins
    image: 'jenkins'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
    network_mode: host
volumes:
  jenkins_home:
    driver: local
