version: '3'
services:
  jenkins:
    container_name: jenkins
    image: 'jenkins'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
volumes:
  jenkins_data:
    driver: local