version: "3"

services:
  elk:
    container_name: elk
    image: sebp/elk
    build: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "12201:12201/udp"
      
#networks:
#  default:
#    external:
#      name: elknet